name: Sync from official

on:
  schedule:
  - cron:  "10 */4 * * *"
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://git.savannah.gnu.org/git/grub.git"
        source_branch: "master"
        destination_branch: "official"
        github_token: ${{ secrets.GITHUB_TOKEN }}
